<?php
$page_title = 'About';
include 'header.php';
?>
<h2>About This Website</h2>

<p>
	The IS Topics Database (BETA!) is, as you might suspect, a database of Independent Study (IS) and other research topics generated by Wooster students, for Wooster students. Discover who is working on a project similar to yours. Find that interdisciplinary partnership that will inform and infuse both of your projects!
</p>
</p>
	Once you have logged in to the site you can share information about your own project or search and browse descriptions of many other CoW student projects that are underway or under consideration. Users can login to the site using their Wooster email address, create a profile, and begin searching using any number of facets.
</p>
<p>
	The database and site are the handiwork of Thomas Matlak (Wooster Class of 2018), who has been periodically toiling since his sophomore year on the project. You can <a href="https://github.com/ThomasMatlak/istopics">find the code repository</a> in his GitHub site. Have an issue or suggestion? File it with the <a href="https://github.com/ThomasMatlak/istopics/issues">issue tracker</a> on GitHub.
</p>
<?php
include 'footer.php';